--- #YAML:1.0
name:                SVN-Pusher
version:             0.04
abstract:            Propagate changesets between two different svn repositories.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    SVN::Core:                     0.37.0
    URI::Escape:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Shlomi Fish <shlomif@iglu.org.il>
